### ISSUE TITLE
一直出localhost/make 404

### ISSUE THREAD

**Issue by Mikasa33** [q809198545/node-sorry#1]
请求错误 localhost:3000/make 404 只生成一个ass文件，没有gif文件

**Comment by q809198545** [comment]
你更新下项目，目前已经修复这BUG了，在路由index,js
 res.redirect('./sorry/');

**Comment by ForlornLily** [comment]
新疑问：第一次进默认sorry页面，还是为404；
应该是因为router.post('/:name/make', Render.action);
此时name是个空，不知道如何解决，请指教_(:з」∠)_

**Comment by q809198545** [comment]
你注意看下url，新版的代码应该都能跳转到http://127.0.0.1:3000/sorry/，如果不行看代码（最后带上/）
router.get('/', function (req, res, next) {
  res.redirect('./sorry/');
});

**Comment by ForlornLily** [comment]
嗯嗯，原因是sorry后面少了"/"，正确应该是ip:3000/sorry/。
谢谢！
